android_mainnet:
  image: greenaddress/android_cordova@sha256:aab8b3a3c339beef738fbdb3f52bf8f1fd3c8f79e2f0727268adb5804c6092c5
  artifacts:
    name: "wallet-cordova-android-release-$CI_COMMIT_REF_NAME"
    when: on_success
    expire_in: 1 hour
    paths:
    - platforms/android/build/outputs/apk/release/*.apk
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./prepare.sh --mainnet
    - cordova prepare android
    - cordova build android --release

android_testnet:
  image: greenaddress/android_cordova@sha256:aab8b3a3c339beef738fbdb3f52bf8f1fd3c8f79e2f0727268adb5804c6092c5
  artifacts:
    name: "wallet-cordova-android-release-$CI_COMMIT_REF_NAME"
    when: on_success
    expire_in: 1 hour
    paths:
    - platforms/android/build/outputs/apk/release/*.apk
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./prepare.sh --testnet
    - cordova prepare android
    - cordova build android --release
    - mv platforms/android/build/outputs/apk/release/android-release-unsigned.apk platforms/android/build/outputs/apk/release/testnet-release-unsigned.apk

ios_mainnet:
  artifacts:
    name: "wallet-cordova-ios-release-$CI_COMMIT_REF_NAME"
    when: on_success
    expire_in: 2 weeks
    paths:
    - platforms/ios/build/device/*.ipa
  tags:
    - osx
  script:
    - cd $CI_PROJECT_DIR
    - ./prepare.sh --mainnet --team $DEVELOPMENT_TEAM $MAINNET_PROVISIONING_PROFILE
    - cordova build ios --device --release
    - ls platforms/ios/build/device/*.ipa

ios_testnet:
  artifacts:
    name: "wallet-cordova-ios-release-$CI_COMMIT_REF_NAME"
    when: on_success
    expire_in: 2 weeks
    paths:
    - platforms/ios/build/device/*.ipa
  tags:
    - osx
  script:
    - cd $CI_PROJECT_DIR
    - ./prepare.sh --testnet --team $DEVELOPMENT_TEAM $TESTNET_PROVISIONING_PROFILE
    - cordova build ios --device --release
    - ls platforms/ios/build/device/*.ipa

package_release:
  tags:
    - garelease
  stage: deploy
  artifacts:
    expire_in: 14 days
    paths:
    - platforms/android/build/outputs/apk/release/*
    when: on_success
  script: cd $CI_PROJECT_DIR/platforms/android/build/outputs/apk/release && /opt/process_release
  dependencies:
  - android_mainnet
  - android_testnet
