android_mainnet:
  image: greenaddress/android_cordova@sha256:ededcb15dd0aff7dc76d2399750efd24de5b7d52cd0c879ac3eb123e6de1be22
  artifacts:
    name: "wallet-cordova-android-release-$CI_COMMIT_REF_NAME"
    when: on_success
    expire_in: 1 hour
    paths:
    - platforms/android/build/outputs/apk/release/*.apk
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./prepare.sh --mainnet
    - cordova prepare android
    - cordova build android --release

android_testnet:
  image: greenaddress/android_cordova@sha256:ededcb15dd0aff7dc76d2399750efd24de5b7d52cd0c879ac3eb123e6de1be22
  artifacts:
    name: "wallet-cordova-android-release-$CI_COMMIT_REF_NAME"
    when: on_success
    expire_in: 1 hour
    paths:
    - platforms/android/build/outputs/apk/release/*.apk
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./prepare.sh --testnet
    - cordova prepare android
    - cordova build android --release
    - mv platforms/android/build/outputs/apk/release/android-release-unsigned.apk platforms/android/build/outputs/apk/release/testnet-release-unsigned.apk

package_release:
  tags:
    - garelease
  stage: deploy
  artifacts:
    expire_in: 14 days
    paths:
    - platforms/android/build/outputs/apk/release/*
    when: on_success
  script: cd $CI_PROJECT_DIR/platforms/android/build/outputs/apk/release && /opt/process_release
  dependencies:
  - android_mainnet
  - android_testnet
