language: generic
matrix:
  include:
    - language: generic
      sudo: required
      services:
        - docker
      script: docker run -v $PWD:/walletcordova greenaddress/android_cordova@sha256:ededcb15dd0aff7dc76d2399750efd24de5b7d52cd0c879ac3eb123e6de1be22
